config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'pages#home'
  resources :gyms, only: [:index, :show] do
    resource :bookmarks, only: [:create, :destroy]
    resources :reviews, only: :create
    resources :wods do
      resources :scores, only: :create
    end
    resources :whiteboard, only: :show
    resources :events
    resources :admins, only: [:create, :destroy]
  end
  get '/views/pages/crossfitwods' => 'pages#crossfitwods'
  resources :bookmarks, only: :index
  # resources :events, except:[:create]
  resources :conversations do
  resources :messages
  end
  get :search, controller: :main
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
#

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  belongs_to :wod
  belongs_to :gym
  validates_presence_of :time
  validates :wod_id, uniqueness: { scope: :user_id, message: "score already posted." }
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  # before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  # def index

  # end

  # GET /scores/1
  # GET /scores/1.json
  # def show
  # end

  # GET /scores/new
  # def new
  #   @score = Score.new
  # end

  # GET /scores/1/edit
  # def edit
  # end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)
    @score.gym = Gym.find(params["gym_id"])
    @score.user = current_user
    @score.wod = Wod.find(params["wod_id"])
    respond_to do |format|
      if @score.save
        format.html { redirect_to gyms_path(@gyms) }
        format.js
      else
        format.html { render 'gyms/show' }
        format.js
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  # def update
  #   respond_to do |format|
  #     if @score.update(score_params)
  #       format.html { redirect_to @score, notice: 'Score was successfully updated.' }
  #       # format.json { render :show, status: :ok, location: @score }
  #     else
  #       format.html { render :edit }
  #       # format.json { render json: @score.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /scores/1
  # DELETE /scores/1.json
  # def destroy
  #   @score.destroy
  #   respond_to do |format|
  #     format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
  #     # format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_score
    #   @score = Score.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:content, :time)
    end
end

app/views/scores/_form.html.erb
<%#= simple_form_for([ gym, wod, score ], remote: true) do |form| %>
  <!-- <div class="form-with-padding"> -->
  <%#= form.input :content, as: :text, label: false  %>
  <%#= form.input :time, as: :datetime, label: false  %>
  <%#= form.button :submit, class: "btn btn-primary btn-sm " %>
  <!-- </div> -->
<%# end %>


<%= simple_form_for(@score, url: gym_wod_scores_path(@gym, wod ), remote: true, method: :post, html: { class: '' })  do |form| %>
<div class="form-row">
    <div class="col">
      <%= form.input :content, as: :string, label: false, class: 'form-control'  %>
    </div>
    <div class="col">
      <span id="other" class="btn-dark btn btn-sm"><i class="far fa-clock"></i>
      <%= form.hidden_field :time, as: :text, label: false %>
    </span>
    </div>
</div>
      <!-- <input type="text" id="datefilter" value="" /> -->
      <!-- <input type="text" name="datetimes" /> -->
  <%#= form.input :time, as: :text, label: false, class: 'form-control' %>
  <%#= form.time_select :time,  { prompt: {hour: 'Choose hour'}, minute_step: 60, ampm: true }, { class: 'form-control' } %>
      <%= form.button :submit, class: "btn btn-primary btn-sm" %>
    <!-- </div> -->
  <!-- </div> -->
<% end %>

app/views/scores/_show.html.erb
<span><%= @score.user.name.split(" ").first %> - <%= @score.content %></span>

app/views/scores/create.js.erb
<% if @score.errors.any? %>
  // console.log('<%= raw @score.errors.full_messages.to_s%>')
  popUpErrors();
<% end %>

<% if @score.wod.scores.pluck(:time).select{ |thing| thing == @score.time}.count >= 2 && !@score.errors.any?%>
      addScore('<%= j render "scores/show", score: @score %>')
      // console.log('in the existing time');
<% end %>

<% if @score.wod.scores.pluck(:time).select{ |thing| thing == @score.time}.count < 2 && !@score.errors.any? %>
    newScore('<%= j render "scores/show", score: @score %>')
    // console.log('in the new time');
<% end %>

<%if !@score.time.blank?%>
  function refreshForm(innerHTML) {
    const newReviewForm = document.getElementById('new_score');
    newReviewForm.innerHTML = innerHTML;
  }

  function addScore(scoreHTML) {


    <% array_of_class_hours = @score.wod.scores.pluck(:time).uniq { |date| date.hour}.map { |thing| thing.hour}.sort %>
    <% group = array_of_class_hours.index(@score.time.hour).to_i %>

    var group = group
    var insertHere = $('.score-id-' + '<%=group%>')[$('.score-id-' + '<%=group%>').length - 1];
    insertHere.insertAdjacentHTML('afterEnd',
    `<div class="card-body text-left score-id-${group}" style="padding-left: 0; font-size: small; padding-top: 6px; padding-bottom: 3px;">
                             ${scoreHTML} <br>
                        </div>`);
  }

  function newScore(scoreHTML) {
    <% array_of_class_hours = @score.wod.scores.pluck(:time).uniq { |date| date.hour}.map { |thing| thing.hour}.sort %>
    <% new_class_hours = array_of_class_hours << @score.time.hour %>
    <% insert_point = new_class_hours.index(@score.time.hour).to_i %>
    var insert_point = insert_point
    var insertHere_two = $( '.class-time-' + '<%= insert_point - 1%>')[0]
    var insertHere_three = $('.card-title')[2]

  <% if insert_point == 0 %>
    insertHere_three.insertAdjacentHTML('afterEnd',
  <% end %>
  <% if insert_point != 0 %>
    insertHere_two.insertAdjacentHTML('afterEnd',
  <% end %>
    `<div class="w-50 class-time-${insert_point}" style="">
     <div style="padding-right: 30px;">
        <div class="card-header font-weight-bold " style="background-color: white;  padding-top: 3px; ">
            <%=@score.time.strftime('%l %P') if !@score.time.blank?%>
        </div>
      </div>
      <div class="card-body text-left score-id-${insert_point}" style="padding-left: 0; font-size: small; padding-top: 6px; padding-bottom: 3px;">
          ${scoreHTML} <br>
      </div>
    </div>`);
  }
<%end%>
function popUpErrors(){
    const insertHere = document.querySelector('#new_score')
    insertHere.insertAdjacentHTML('beforebegin',

  `<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <% @score.errors.full_messages.each do |error| %>
      <%= raw error %> <br>
    <% end %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  </div>`
      );
  }

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scores</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>