config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'pages#home'
  resources :gyms, only: [:index, :show] do
    resource :bookmarks, only: [:create, :destroy]
    resources :reviews, only: :create
    resources :wods do
      resources :scores, only: :create
    end
    resources :whiteboard, only: :show
    resources :events
    resources :admins, only: [:create, :destroy]
  end
  get '/views/pages/crossfitwods' => 'pages#crossfitwods'
  resources :bookmarks, only: :index
  # resources :events, except:[:create]
  resources :conversations do
  resources :messages
  end
  get :search, controller: :main
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
#

app/views/shared/_bootstrap_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #1a3263;" >
<!--   <a class="navbar-brand" href="https://gngbase.com">
    <img src="<%#= image_url 'logo.png' %>" width="45" height="45" alt="logo">
  </a> -->
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", height: 45, width:45, alt: 'logo' %>
  <% end %>
  <%= render 'shared/search_bar' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
  <% if user_signed_in? %>
        <a class="nav-item nav-link disabled" href="#">Schedule</a>
        <%= link_to 'Messages', conversations_path, class: "nav-item nav-link" %>
        <a class="nav-item nav-link disabled" href="#">Membership</a>
        <%= link_to 'Saved', bookmarks_path, class: "nav-item nav-link"  %>
        <%= link_to 'WODs', views_pages_crossfitwods_path, class: "nav-item nav-link"  %>
        <div class="dropdown">
        <% if !current_user.image.blank? %>
          <%= image_tag current_user.image, class: "avatar-small dropdown-toggle", id: "dropdownMenuButton", "data-toggle" => "dropdown"%>
        <% else %>
          <button class="btn btn-link dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-decoration: none;">
            Account
          </button>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <% if !current_user.name.blank? %>
              <p class="text-center"><%= current_user.name %></p>
              <div class="dropdown-divider"></div>
              <% end %>
            <%= link_to t(".log_out", default: "Logout"), destroy_user_session_path, class: "dropdown-item text-center btn btn-danger" %>
          </div>
        </div>
  <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-item nav-link" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-item nav-link" %>
  <% end %>
      </div>
      </div>
</nav>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <!-- <a href="#"><i class="fa fa-github"></i></a> -->
    <a href="https://www.instagram.com/gngbase/"><i class="fab fa-instagram"></i></a>
    <!-- <a href="#"><i class="fa fa-facebook"></i></a> -->
    <!-- <a href="#"><i class="fa fa-twitter"></i></a> -->
    <!-- <a href="#"><i class="fa fa-linkedin"></i></a> -->
  </div>
  <div class="footer-copyright">
    This is made with <i class="fa fa-heart"></i> by a Le Wagon graduate
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

      <!-- Search Method -->
      <%#= form_tag gyms_path, method: :get do %>
      <%#= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Type a city name"
      %>
      <%# end %>
      <!-- Form Method -->
    <!-- <div class="search-bar"> -->
    <%#= simple_form_for(@gym, as: :gym, method: :get, url: gyms_path, wrapper: :inline_form, html: { class: 'form-inline' }) do |f| %>
    <%#= f.input :address, placeholder: 'Try "Barcelona"' %>
    <%#= f.submit 'Find gyms', class: "btn btn-primary" %>
    <%# end %>
    <!-- </div> -->
    <%= render 'shared/search_bar' %>
    <%#= simple_form_for(@gym) do |f| %>
    <!-- <div class="form-inputs"> -->
    <%#= f.input :address, label: false, url: :gyms_path, method: :get %>
    <%#= f.button :submit %>
    <!-- </div> -->

    <%# end %>
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://i.pravatar.cc/300", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%#= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
 <!--  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div> -->
</div>

app/views/shared/_search_bar.html.erb
  <%= simple_form_for(Gym.new, as: :gym, method: :get, url: gyms_path, wrapper: :inline_form, html: { class: 'form-inline flex-grow-1' }) do |f| %>
     <div class="form-group flex-grow-1" style="margin-bottom: 0px;">
        <!-- <i class="fas fa-search"></i> -->
        <%= f.input :address, placeholder: 'Try "Barcelona"'  %>
        <%#= f.submit 'Find', class: "btn btn-primary", id: "find-gyms"%>
     </div>
  <% end %>

        <%#= button_tag type: 'submit', class: "btn btn-primary",id: "find-gyms" do %>
              <!-- <i class="fas fa-search"></i> -->
          <%# end %>