config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'pages#home'
  resources :gyms, only: [:index, :show] do
    resource :bookmarks, only: [:create, :destroy]
    resources :reviews, only: :create
    resources :wods do
      resources :scores, only: :create
    end
    resources :whiteboard, only: :show
    resources :events
    resources :admins, only: [:create, :destroy]
  end
  get '/views/pages/crossfitwods' => 'pages#crossfitwods'
  resources :bookmarks, only: :index
  # resources :events, except:[:create]
  resources :conversations do
  resources :messages
  end
  get :search, controller: :main
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
#

app/models/gym.rb
class Gym < ApplicationRecord
  belongs_to :city, counter_cache: true
  belongs_to :country, counter_cache: true
  has_many :bookings
  has_many :bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :admins, dependent: :destroy
  has_many :scores, dependent: :destroy
  has_one :whiteboard
  # belongs_to :user
  has_many :users, through: :admin
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def self.get(gym_name)
    self.where(name: gym_name).first
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  require 'open-uri'
  require 'nokogiri'
  require 'i18n'
  require 'savon'
  # require 'google_places'
  skip_before_action :authenticate_user!, only: [:index, :show]

  def media_hash_to_object(array_of_hashes)
    @array_of_posts = []
    array_of_hashes.each do |dumb|
    post = OpenStruct.new
    post.id = dumb["node"]["id"]
    post.type = dumb["node"]["__typename"]
    post.caption = dumb["node"]["edge_media_to_caption"]['edges'][0]['node']['text'] if !dumb["node"]['edge_media_to_caption']['edges'].blank?
    post.time = Time.at(dumb["node"]['taken_at_timestamp']).strftime("%B %d, %Y")
    post.picture = OpenStruct.new
    post.picture.small = dumb["node"]["thumbnail_resources"][0]["src"]
    post.picture.medium = dumb["node"]["thumbnail_resources"][1]["src"]
    post.picture.large = dumb["node"]["thumbnail_resources"][2]["src"]
    post.picture.xl = dumb["node"]["thumbnail_resources"][3]["src"]
    post.picture.xxl = dumb["node"]["thumbnail_resources"][4]["src"]
    post.likes = dumb["node"]['edge_liked_by']['count']
    post.owner = OpenStruct.new
    post.owner.id = dumb["node"]['owner']['id']
    post.owner.username = @profile['user']['username'] if ! @profile.blank?
    post.owner.profile_pic = @profile['user']['profile_pic_url'] if ! @profile.blank?
    post.owner.follower_count = @profile['user']['follower_count'] if ! @profile.blank?
    post.owner.follower_count_text = @profile['user']['byline'] if ! @profile.blank?
    @array_of_posts << post
    end

  end

  def instagram_web_search(gym_instance)
    url_search = "https://www.instagram.com/web/search/topsearch/?context=blended&query=#{@gym.name}"
    user_serialized = open(I18n.transliterate(url_search)).read
    @user = JSON.parse(user_serialized)
  end

  def instagram_user_method(instagram_web_search_result)
      @sorted = @user.first[1].sort_by { |each| each["user"]["follower_count"] }
      @profile = @sorted.last
      @username = @profile["user"]["username"]
      @username = @gym.username if !@gym.username.blank?
   # search for gym details
      url = "https://www.instagram.com/#{@username}/"

      html_file = open(url).read
      html_doc = Nokogiri::HTML(html_file)
      element = html_doc.text.strip
      @results = []
      html_doc.search('script').each do |element|
        @results << element
      end
      if @results[4].children.text.strip.chomp(";").last(-21) == "oaded(window._sharedData)"

        @instagram = JSON.parse(@results[3].children.text.strip.chomp(";").last(-21))
      else
        @instagram = JSON.parse(@results[4].children.text.strip.chomp(";").last(-21))
      end
      # @instagram = JSON.parse(@results[4].children.text.strip.chomp(";").last(-21))
      @media = @instagram["entry_data"]["ProfilePage"][0]["graphql"]["user"]["edge_owner_to_timeline_media"]["edges"]
      media_hash_to_object(@media)
      @user = @instagram["entry_data"]["ProfilePage"][0]["graphql"]["user"]
  end

  def instagram_place_method(instagram_web_search_result)

      @pk =  @user["places"][0]["place"]["location"]["pk"]
      url = "https://www.instagram.com/explore/locations/#{@pk}/#{@gym.name.split[0]}-#{@gym.name.split[1]}/"
      html_file = open(I18n.transliterate(url)).read
      html_doc = Nokogiri::HTML(html_file)
      element = html_doc.text.strip
      @results = []
      html_doc.search('script').each do |element|
        @results << element

        end
      @instagram = JSON.parse(@results[3].children.text.strip.chomp(";").last(-21))
      @media = @instagram["entry_data"]["LocationsPage"][0]["graphql"]["location"]["edge_location_to_media"]["edges"].first(12)
      media_hash_to_object(@media)
  end

  def instagram_hashtag_method(instagram_web_search_result)

      hashtag = @user["hashtags"][0]["hashtag"]["name"]
      url = "https://www.instagram.com/explore/tags/#{hashtag}/"
      html_file = open(I18n.transliterate(url)).read
      html_doc = Nokogiri::HTML(html_file)
      element = html_doc.text.strip
      @results = []
      html_doc.search('script').each do |element|
        @results << element

        end
      @instagram = JSON.parse(@results[4].children.text.strip.chomp(";").last(-21))
      @media =  @instagram["entry_data"]["TagPage"][0]["graphql"]["hashtag"]["edge_hashtag_to_media"]["edges"].first(12)
      media_hash_to_object(@media)
  end




  def show
    @score = Score.new
    @wod = Wod.new
    @wods = Wod.where(gym_id: params["id"])
    @admin = Admin.new
    @bookmark = Bookmark.new
    @review = Review.new
    @events = Event.where(gym_id: params["id"])
    @gyms = []
    @gym = Gym.find(params["id"])
    @gyms << @gym
        @markers = @gyms.map do |gym|
        {
          lat: gym.latitude,
          lng: gym.longitude
          # ,
          # infoWindow: { content: render_to_string(partial: "/gyms/map_box", locals: { gym: gym }) }
        }
      end
# -----search for gym possible instagram ids and pick the one with most followers
    instagram_web_search(@gym)
# -------------- initial get to instagram above with gym name --------------
  # !@gym.username.blank?
  if !@gym.username.present? && !@gym.igplace.present? && !@gym.hashtag.present?

    if !@user["users"].blank?

    instagram_user_method(@user)
# --------------work with users above this line --------------------
    elsif !@user["places"].blank?
    instagram_place_method(@user)
      #
 # --------------work with places above this line --------------------
    else
    instagram_hashtag_method(@user)
    end
#--------------line where three options converge-----------------------
  elsif @gym.username.present?
    @username = @gym.username
   # search for gym details
      url = "https://www.instagram.com/#{@username}/"

      html_file = open(url).read
      html_doc = Nokogiri::HTML(html_file)
      element = html_doc.text.strip
      @results = []
      html_doc.search('script').each do |element|
        @results << element
      end
      @instagram = JSON.parse(@results[4].children.text.strip.chomp(";").last(-21))
      @media = @instagram["entry_data"]["ProfilePage"][0]["graphql"]["user"]["edge_owner_to_timeline_media"]["edges"]
      media_hash_to_object(@media)
      @user = @instagram["entry_data"]["ProfilePage"][0]["graphql"]["user"]
      @profile = @instagram["entry_data"]["ProfilePage"][0]["graphql"]
  elsif @gym.igplace.present?
      @pk = @gym.igplace
      url = "https://www.instagram.com/explore/locations/#{@pk}/#{@gym.name.split[0]}-#{@gym.name.split[1]}/"
      html_file = open(I18n.transliterate(url)).read
      html_doc = Nokogiri::HTML(html_file)
      element = html_doc.text.strip
      @results = []
      html_doc.search('script').each do |element|
        @results << element

        end
      @instagram = JSON.parse(@results[4].children.text.strip.chomp(";").last(-21))
      @media = @instagram["entry_data"]["LocationsPage"][0]["graphql"]["location"]["edge_location_to_media"]["edges"].first(12)
      media_hash_to_object(@media)
  elsif @gym.hashtag.present?
      hashtag = @gym.hashtag
      url = "https://www.instagram.com/explore/tags/#{hashtag}/"
      html_file = open(I18n.transliterate(url)).read
      html_doc = Nokogiri::HTML(html_file)
      element = html_doc.text.strip
      @results = []
      html_doc.search('script').each do |element|
        @results << element

        end
      @instagram = JSON.parse(@results[4].children.text.strip.chomp(";").last(-21))
      @media =  @instagram["entry_data"]["TagPage"][0]["graphql"]["hashtag"]["edge_hashtag_to_media"]["edges"].first(12)
      media_hash_to_object(@media)
  end
      @bio = @user["biography"]
     # access here to an array with the photos and information post level
# ------------google places section -------------------------------------
     @client = GooglePlaces::Client.new(ENV['GOOGLE_API_SERVER_KEY'])
     spot = @client.spots(@gym.latitude, @gym.longitude, :name => @gym.name)
     if spot.blank?
       spot = @client.spots_by_query("#{@gym.name} near #{@gym.city.name} #{@gym.city.state.to_s}")
     end
     if !spot.blank?
      spot_id = spot.first.place_id
      @spot = @client.spot(spot_id)
      if !@spot.opening_hours.blank?
        @hours = @spot.opening_hours["weekday_text"]
        @open_now = @spot.opening_hours["open_now"]
      end

     end
# -------------------------------------------------
  end


  def index
      @gym = Gym.new
    if params.has_key?(:city) & !params["state"].blank?
      @gyms = Gym.joins(:country , :city).where('cities.name' => params["city"], 'countries.name' => params["country"], 'cities.state' => params["state"])
    elsif params.has_key?(:city) && params["state"].blank?
      @gyms = Gym.joins(:country , :city).where('cities.name' => params["city"], 'countries.name' => params["country"])
      # binding.pry
      # @gyms = Gym.joins(:city).where('cities.name' => params["profile_card"])
      # @gyms = Gym.near(params["profile_card"],10)

    # the first search term is tied to the banner search button
    elsif !params["gym"].blank? && !params["gym"]["address"].blank?
        @gyms = Gym.near(params["gym"]["address"],10)
          if @gyms.blank?
            @gyms = Gym.near(params["gym"]["address"],30)
          end
          if @gyms.blank? || params["gym"]["address"].split.count == 1
            @gyms = Gym.joins(:country).where('countries.name' => params["gym"]["address"]).first(30)
          end

    else
      @city = City.all.sample
      @gyms = Gym.joins(:city).where('cities.name' => @city.name)

    end


        @markers = @gyms.map do |gym|
        {
          lat: gym.latitude,
          lng: gym.longitude,
          infoWindow: render_to_string(partial: "/gyms/map_box", locals: { gym: gym })
          # infoWindow: { content: render_to_string(partial: "/gyms/map_box", locals: { gym: gym }) }
        }
      end
  end
end
    #   sql_query = " \
    #     cities.name @@ :query \
    #   "

app/views/gyms/_map_box.html.erb
  <%#= image_tag "https://maps.googleapis.com/maps/api/streetview?size=600x300&location=#{gym.latitude},#{gym.longitude}&heading=151.78&pitch=-0.76&key=#{ENV['GOOGLE_API_BROWSER_KEY']}", class: "picture" %>

<!-- <div style="font-weight: bold;"><%#= link_to gym.name, gym_path(gym) %></div> -->
<%#= link_to 'website', gym.website, target: '_blank' %>

<div class="container" >
   <div class="card">
    <img class="card-img-top" src='https://maps.googleapis.com/maps/api/streetview?size=600x300&location=<%= gym.latitude %>,<%= gym.longitude %>&heading=151.78&pitch=-0.76&key=<%= "#{ENV['GOOGLE_API_BROWSER_KEY']}" %>' alt="Card image cap">
    <div class="card-body">
      <h6 class="card-subtitle text-truncate"><%= gym.name %></h6>
      <small class="text-muted text-truncate"> <%= gym.city.name %> <%= gym.country.name %></small>
      <!-- <p class="card-text"><%#= gym.city.name %></p> -->
    </div>
    <!-- <div class="card-footer"> -->

    <!-- </div> -->
    <div class="card-link">
          <%= link_to "Link", gym_path(gym), :class=> "card-link" %>
        </div>
  </div>
</div>

app/views/gyms/index.html.erb
<% if !@gyms.first.blank? %>
<h3 class=""><%= "#{@gyms.first.city.name} #{@gyms.first.city.state.to_s}"%></h3>
<% end %>
<div class="main-container">
  <div class="d-flex flex-md-row flex-column mb-3">
  <div class="p-2 bd-highlight ">
  <!-- <div class="cards-container"> -->
      <%= render 'components/cards' %>
  </div>
  <div class="p-2 bd-highlight information ">
  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
 <!--  <div
  id="map" class="hidden-xs"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  ></div> -->
</div>
  <!-- </div> -->
<!--       <%#= form_tag gyms_path, method: :get do %>
      <%#= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Type a city name"
      %>
    <#% end %> -->


  </div>
</div>

app/views/gyms/show.html.erb
      <%#= render 'components/navs' %>
<div class="main-container">
  <div class="d-flex flex-md-row flex-column-reverse mb-3">
  <div class="p-2 bd-highlight flex-shrink-1 flex-grow-1">

      <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="pills-Photos-tab" data-toggle="pill" href="#pills-Photos" role="tab" aria-controls="pills-Photos" aria-selected="true">Photos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="pills-WOD-tab" data-toggle="pill" href="#pills-WOD" role="tab" aria-controls="pills-WOD" aria-selected="false">WODs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="pills-scores-tab" data-toggle="pill" href="#pills-scores" role="tab" aria-controls="pills-scores" aria-selected="false">Board</a>
        </li>
        <% if @gym.admins.users.include?(current_user) %>
          <li class="nav-item">
            <a class="nav-link" id="pills-Make-WOD-tab" data-toggle="pill" href="#pills-Make-WOD" role="tab" aria-controls="pills-Make-WOD" aria-selected="false">Box Admin</a>
          </li>
        <% end %>
      </ul>
<!-----pills content bellow---------pils control above----- -->
      <div class="tab-content" id="pills-tabContent">

        <div class="tab-pane fade show active" id="pills-Photos" role="tabpanel" aria-labelledby="pills-home-tab">
          <%= render 'components/instagram_cards' %>
        </div>

        <div class="tab-pane fade" id="pills-WOD" role="tabpanel" aria-labelledby="pills-profile-tab">
          <%= render 'wods/index' %>
        </div>

        <div class="tab-pane fade" id="pills-scores" role="tabpanel" aria-labelledby="pills-scores-tab">
          <%= render 'whiteboards/show' %>
        </div>

        <div class="tab-pane fade" id="pills-Make-WOD" role="tabpanel" aria-labelledby="pills-contact-tab">

          <div class="col-lg-7">
            <h5>Make a WOD</h5>
            <%= render 'wods/form', gym: @gym, wod: @wod %>
            <div class="bookings">
              <h3 class="text-center" style="padding-top:0">Create an Event<i class="fas fa-arrow-down"></i></h3>
                <div class='calendar' id="<%=params["id"]%>" ></div>
            </div>
          </div>
        </div>

      </div>

      <!-- -end of pills buttons------- -->
      <%#= render 'components/instagram_cards' %>
  </div>
  <div class="p-2 bd-highlight information ">
  <!-- <div class="information"> -->

    <!-- <div class="show-container"> -->
      <%# if  !@profile.blank? %>

        <%#= image_tag @profile["user"]["profile_pic_url"], :class=> "avatar-large" %>

      <%# end %>

  <div class="intro">

 <% if  !@profile.blank? %>
        <%#= image_tag @profile["user"]["profile_pic_url"], :class=> "avatar-large-show" %>
      <% end %>
    <div class="d-flex flex-row">
      <div class="p-2">
        <h2><%= @gym.name %></h2>
      </div>
      <div class="p-2">
        <% if user_signed_in? %>
          <%= render 'bookmarks/form', gym: @gym, bookmark: @bookmark %>
         <% end %>
      </div>
    </div>

     <%= @user["biography"] %>
     <!-- <i class="far fa-bookmark"></i> -->
  </div>

<!--  <div class="classes">
      <p>Classes for <%#= @location_schedule[0]["start_date_time"].split("  ")[0] %></p>
    <ul class="hours">
    <%# @location_schedule.each do |thing| %>
      <div class="element list-inline">
      <li><strong> <%#= thing["class_name"] %></strong></li>
      <li>Start: <%#= thing["start_date_time"].split("  ")[1] %></li>
      <li>End: <%#= thing["end_date_time"].split("  ")[1] %></li>
      </div>
    <%# end %>
    </ul>
  </div> -->
<% if !@spot.blank? %>
  <p style="margin-bottom: 3px;">
    <% if !@profile.blank? %>
      <%= link_to "https://www.instagram.com/#{@profile["user"]["username"]}", target: '_blank' do %>
          <i class="fab fa-instagram"></i> <%= @username %>
      <% end %> <br>
    <% end %>
  <!-- </p> -->
  <!-- <p> -->
    <%= link_to @gym.website, target: '_blank' do %>
      <i class="fas fa-link"></i> <%=  @gym.website.split("www.").second.blank? ? @gym.website.split("//").second : @gym.website.split("www.").second  %>
      <% end %> <br>
    <%= @spot.formatted_address %>
  <%= link_to @spot.url, target: '_blank' do %>
  <i class="fas fa-map-marker-alt fa-lg"></i> <%= "Google Maps" %>
  <% end %> <br>
  <i class="fas fa-phone-volume fa-lg"></i> <%= @spot.international_phone_number %> <br>
  <!-- <p> <i class="far fa-clock fa-lg"></i></p> -->
  </p>
  <!-- <p> -->
    <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    <!-- <i class="far fa-clock fa-lg"></i> -->
     Hours
    </button>
    <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#multiCollapseExample2" aria-expanded="false" aria-controls="multiCollapseExample2">User Reviews
    </button>
    <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#multiCollapseExample3" aria-expanded="false" aria-controls="multiCollapseExample3">Pricing
    </button>
    <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#multiCollapseExample4" aria-expanded="false" aria-controls="multiCollapseExample4">Contact
    </button>
  <!-- </p> -->
    <div class="collapse" id="collapseExample">
    <div class="card card-body" style="background-color: none;">
      <div class="hours">
        <% if !@hours.blank? %>
        <table class="table table-sm">
          <thead>
          </thead>
          <tbody>
          <% @hours.each do |thing| %>
            <tr>
              <th scope="row" style=" width: 103px;"><%= thing.partition(":").first %></th>
              <td><%= thing.partition(":").third.delete(' ') %></td>
            </tr>
          <% end %>
          </tbody>
        </table>

        <% end %>
      </div>
<% end %>
    </div>
</div>
    <div class="collapse multi-collapse" id="multiCollapseExample2">
      <div class="card card-body">
           <!-- reviews------------------------ -->
    <div class="google-reviews">
      <h3 id="parent-review" style="padding-top: 0px;">User Reviews</h3>
      <% if @gym.reviews.blank? %>
        <span id="review-notice">Be the first to leave a review for <%= @gym.name %></span>
      <% end %>
      <%# @spot.reviews.first(3).each do |review| %>
      <% @gym.reviews.last(3).each do |review| %>
      <div class="google-review">
        <div class=' <%= ["bg-primary", "bg-success", "bg-warning"].sample %>' style="padding-left: 4px;">
          <%#= image_tag review.profile_photo_url, :class=>
          "avatar-google" %>
          <span class=""><%= review.user.name %></span>
        </div>
        <!-- <span class="initials"><%= review.user.name.capitalize %></span> -->

        <div class="review-text">
          <%#= review.text.split(".")[0] %>
          <% if @gym.reviews.blank? %>
          <span id="review-notice">Be the first to leave a review for <%= @gym.name %></span>
          <% else %>
          <%= render 'reviews/show', review: review %>
          <% end %>
        </div>
      </div>
      <% end %>
      <%= render 'reviews/form', gym: @gym, review: @review if user_signed_in? %>
    </div>
    <!-- end of reviews--------------------- -->
      </div>
    </div>
    <div class="collapse multi-collapse" id="multiCollapseExample3">
      <div class="card card-body">
        Prices
      </div>
    </div>
    <div class="collapse multi-collapse" id="multiCollapseExample4">
      <div class="card card-body">
      <% if !@gym.admins.blank? && user_signed_in?%>
        <%= link_to  conversations_path(sender_id: current_user.id, recipient_id: @gym.admins.first.user_id), method: :post do %>
            <i class="far fa-envelope"></i> <%=User.find(@gym.admins.first.user_id).name  %>
          <% end %>

      <% else %>
          <%= "Sign in to become an admin for this gym" if !user_signed_in? %>
          <div id="admins">
            <% if !@gym.admins.users.include?(current_user) && user_signed_in?%>
            Become an admin for this gym
            <%= render 'admins/form' %>
            <% end %>

          </div>
      <% end %>

      </div>
    </div>
    <!-- , method: :delete, id: "delete-conversation"  -->

    <!-- <div id="reviews"> -->
      <%# if @gym.reviews.blank? %>
        <!-- Be the first to leave a review for <%#= @gym.name %> -->
      <%# else %>
        <%# @gym.reviews.last(5).each do |review| %>
        <%#= render 'reviews/show', review: review %>
        <%# end %>
      <%# end %>
    <!-- </div> -->

 <!--      <div
  id="map" class=" show-map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  ></div> -->
  <!-- </div> -->
  <!-- </div> -->

<!--   <div id="admins">
    <%# if !@gym.admins.users.include?(current_user) && user_signed_in?%>
      <%#= render 'admins/form' %>
    <%# end %>
  </div> -->

  </div>
</div>
    <!-- <div class="cards-container"> -->
<%# binding.pry %>
<%#= image_tag @profile["user"]["profile_pic_url"] %>
<%#= render 'components/instagram_cards' %>
    <!-- </div> -->




</div>
<!-- <div
  id="map" class="show-map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  ></div> -->
</div>